sources:
  - name: coupon-finance
    handler:
      graphql:
        endpoint: '{context.url:http://dev-subgraph.coupon.finance:8000/subgraphs/name/coupon-subgraph-prod}'
  - name: coupon-finance-point
    handler:
      graphql:
        endpoint: '{context.url:http://dev-subgraph.coupon.finance:8000/subgraphs/name/coupon-point-subgraph-prod}'

documents:
  - ./apis/**/*.graphql
  - ./__tests__/**/*.graphql


codegen:
  contextType: 'MeshContext & { url: string }'
