sources:
  - name: coupon-finance
    handler:
      graphql:
        endpoint: '{context.url:https://dev-subgraph.coupon.finance/subgraphs/name/coupon-subgraph-prod}'
#  - name: coupon-finance-point
#    handler:
#      graphql:
#        endpoint: '{context.url:https://api.studio.thegraph.com/query/49804/coupon-point-subgraph/v1}'

documents:
  - ./apis/**/*.graphql
  - ./__tests__/**/*.graphql


codegen:
  contextType: 'MeshContext & { url: string }'
